### ISSUE TITLE
Unhandled Exception: MissingPluginException on RaspberryPi (flutter-pi)

### ISSUE THREAD

**Issue by Progressia** [hpdragon1618/flutter_gstreamer_player#3]
After compile app as:

$flutter build bundle

for Raspbery Pi under flutter-pi

and run app

I got this error

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method PlayerRegisterTexture on channel flutter_gstreamer_player)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
<asynchronous suspension>
#1      GstPlayerTextureController.initialize (package:flutter_gstreamer_player/flutter_gstreamer_player.dart:18:17)
<asynchronous suspension>
#2      _GstPlayerState.initializeController (package:flutter_gstreamer_player/flutter_gstreamer_player.dart:60:5)
<asynchronous suspension>

It's mean plugin doesn't exist after compile app? On desktop works.

**Comment by hpdragon1618** [comment]
Hi @Progressia,

I have not used flutter-pi so my knowledge about it may limited.

About your error, it is usually occur when the platform side of the plugin does not support the method channel that the dart side is requesting.
So, in your case, to my understanding, flutter-pi is acting as another platform (beside flutter official supported platform like android, ios, linux, ...). If this is the case, flutter gstreamer player does not support flutter-pi at the moment, unfortunately.

But, flutter does support arm linux. You should be able to run flutter gstreamer player plugin using official flutter framework on SoC like Raspberry, If your use case doesn't require to use flutter-pi.

I'm closing the issue, feel free to reach out if you have any concern.
